suppressPackageStartupMessages({
library("SummarizedExperiment")
library("tidyverse")
library("DEP")
library("testthat")
library("shiny")
library("shinydashboard")
library("shinyjs")
library("shinyalert")
library("ComplexHeatmap")
library("dplyr")
library("limma")
library("DT")
library("ggrepel")
library("httr")
library("rjson")
library("svglite")
library("ensembldb")
library(EnsDb.Hsapiens.v86)
library("conflicted")
library("plotly")
library("shinyWidgets")
library("ggVennDiagram")
library("rhandsontable")
library("shinyBS") 
library("shinycssloaders") 
library("shiny.info")
library("fastcluster")
library("factoextra")
})


options(shiny.reactlog=TRUE)

conflict_prefer("box", "shinydashboard")
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("desc", "dplyr")
conflict_prefer("setdiff","base") #Added
conflict_prefer("intersect", "base") #Added

source("R/functions.R")
source("R/volcano_function.R")
source("R/customized.R")
source("R/tests.R")
source("R/demo_functions.R")
source("R/enrichment_functions.R")
source("R/filter.R")
source("R/transform_spectro.R")
source("R/LFQpep_to_TMTpep.R")